formulario/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mascotas/', include('apps.Mascota.urls')),
    path('adopcion/', include('apps.adopcion.urls')),
]

apps/Mascota/models.py
from django.db import models
from  apps.adopcion.models import Person

# Create your models here.
SEX_CHOICES = (
    ('', 'Selecciona un sexo'),
    ('M', 'Macho'),
    ('H', 'Hembra')
)


class Pet(models.Model):
    name = models.CharField(max_length=50)
    sex = models.CharField(max_length=10, choices=SEX_CHOICES, default=None)
    aproximated_ege= models.IntegerField()
    rescue_date = models.DateField()
    persons = models.ForeignKey(Person, null=True, blank=True, on_delete=models.CASCADE)
    
    def __str__(self):
        return '{}'.format(self.name)
    

apps/adopcion/models.py
from django.db import models

# Create your models here.

SORT_CHOICES = (
    ('', 'Selecciona tipo de Telefono'),
    ('Fijo','CASA'),
    ('Movil', 'CELULAR'),
)
    

class Person(models.Model):
    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    age = models.IntegerField()
    email = models.EmailField()

    def __str__(self):
        return '{} {}'.format(self.name, self.last_name)


class Telephone(models.Model):
    Persons = models.ForeignKey(Person,null=True, blank=True, on_delete=models.CASCADE)
    sort = models.CharField(max_length=6, choices=SORT_CHOICES, default=None)
    number = models.CharField(max_length=12)

    def __str__(self):
        return "{}".format(self.number)

templates/actualizar_mascota.html
{% extends 'base.html' %}

{% block content %}
    <form method='Post'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='Guardar'/>
    </form>
{% endblock %}

templates/actualizar_persona.html
{% extends 'base.html' %}

{% block content %}
    <span style="font-size:22px; font-style:italic;" class="d-flex justify-content-center font-weight-lighter mx-auto mt-5">
        <p> <strong>Editar Persona:</strong></p>
    </span>
    <section class="col-12 col-md-8 mx-auto">
    
        <form method="Post">
            {% csrf_token %}

            {{form.as_p}}
            <p>Telefono:</p><hr>
            {{form2.management_form}}
            {% for tel in form2.forms %}
                {{tel.id}}  
                <p>
                    {{tel.sort}}
                </p>
                <p>
                    {{tel.number}}
                </p>
                {% if tel.number.value %}    
                    {{tel.DELETE.label_tag}} {{tel.DELETE}}
                {% endif %}
               
            {% endfor %}    
            
            <button type="button" id="btnNuevoTel" class="btn btn-primary">Agregar Telefono</button>
            <span class="d-flex justify-content-center mb-5">
                <input type="submit" value="Guardar" class="btn btn-success">
            </span>
        </form>
    </section>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Raleway&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Adopcion</title>
</head>
<body class="container-fluid">
    <header class="row header d-flex flex-nowrap justify-content-around align-items-center">
        <a href="{% url 'mascotas_listar'%}">
            <h1 class="col-8 display1">
                Adopcion <strong>Mascotas<sup><i class="fa fa-paw" aria-hidden="true"></i></sup></strong>
            </h1>
        </a>
        <nav class="d-none d-md-flex menu col-12 col-md-4">
            <ul class="d-flex justify-content-between w-100">
                <a href="{% url 'personas_listar' %}"><li>Personas</li></a>
                <a href="{% url 'mascotas_listar' %}"><li>Mascotas</li></a>
                <a href="#"><li>Adopta</li></a>
                <a href="#"><li>Reporte</li></a>
            </ul>
        </nav>
        <div class="d-flex icon-menu d-md-none d-lg-none d-xl-none justify-content-center">
            <i class="fa fa-bars" aria-hidden="true"></i>
        </div>
    </header>

    <section class="row content">
        <section class="col-12 col-md-8 mx-auto bg-color">
            {% block content %}
            {% endblock %}
        </section>
    </section>

    <section class="row footer d-flex justify-content-around align-items-center">
        <section>
            <h4>
                    ADOPTA UNA MASCOTA
            </h4>
            <h5>
                Registrate
            </h5>
        </section>
        <section>
            <p>Direccion: AV. San Juaquin S/n. Colonia Anty</p>
            <p>E-mail: adoptaaunamascota@adoptar.com.mx</p>
            <p>Telefono: 55 999 456 23</p>
            <p>Todos los derechos reservados Adopta una Mascota<sup>&copy;</sup></p>
        </section>
        
    </section>

    <script src="{% static 'js/script.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/crear_mascota.html
{% extends 'base.html' %}

{% block content %}
    <form method='Post'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Guardar"/>
    </form>
{% endblock %}

templates/crear_persona.html
{% extends 'base.html' %}

{% block content %}
    <span style="font-size:22px; font-style:italic;" class="d-flex justify-content-center font-weight-lighter mx-auto mt-5">
        <p> <strong>Registro Persona:</strong></p>
    </span>
    <section class="col-12 col-md-8 mx-auto">
    
        <form method="Post">
            {% csrf_token %}

            {{form.as_p}}
            <p>Telefono:</p><hr>
            {{form2.management_form}}
            {% for tel in form2 %}
                <p>
                    {{tel.sort}}
                </p>
                
                <p>
                    {{tel.number}}
                </p> 
            
            {% endfor %}
            
            
            <button type="button" id="btnNuevoTel" class="btn btn-primary">Agregar Telefono</button>
            <span class="d-flex justify-content-center mb-5">
                <input type="submit" value="Guardar" class="btn btn-success">
            </span>
        </form>
    </section>
{% endblock %}

templates/delete_mascota.html
{% extends 'base.html' %}

{% block content %}
<section class="col-12 col-md-6 mx-auto mt-5">
    <h1>Quieres ELIMINAR a {{object}}?</h1>
    <form method="Post">
        {% csrf_token %}
        <input type="submit" value="Si. Eliminat" class="btn btn-danger">
        <a href="{% url 'mascotas_listar' %}" class="btn btn-info" autofocus>Cancelar</a>
    </form>
</section>
{% endblock %}

templates/detail_mascota.html
{% extends 'base.html' %}
{% block content%}
<section class="col-12 col-md-8 mx-auto">
    {% if object %}
        <section class="alert alert-light w-md-75 mx-auto mt-5" role="alert">
            <span style="font-size:22px; font-style:italic;" class="d-flex title justify-content-center font-weight-lighter mx-auto">
              <p> <strong>Datos Mascota:</strong></p>
            </span>
            <p style="font-size:22px;" class="font-weight-lighter">Nombre: {{object.name|upper}}</p>
            <p style="font-size:22px;" class="font-weight-lighter">Sexo: {{object.get_sex_display}}</p>
            <p style="font-size:22px;" class="font-weight-lighter">Edad: {{object.aproximated_ege}} años</p>
            <section style="font-size:15px; font-style:italic;" class="d-flex justyfy-content-between font-weight-lighter">
                <p style="margin: 0;">Rescatado el: {{object.rescue_date}}</p>
            </section>
            <hr>
            <section style="display: flex; justify-content: space-between;">
                <section>
                 
                    <i><a style="font-size: 10px;" class="btn btn-light" href="{% url 'mascota_actualizar' pk=object.pk  %}" role="button">EDITAR</a></i>
                    <button type="button" class="btn btn-light" data-toggle="modal" data-target="#exampleModal" style="font-size: 10px;">
                      ELIMINAR
                    </button>
                   
                </section>
                {% if object.persons%}
                    <p>Adoptado por: {{ object.persons|upper }}</p>
                    {% else %}
                    <p>Disponible para Adoptar</p>
                {% endif %}
            </section>
        </section>
    {% else %}
    <h1>No se encontro mascota</h1>
    {% endif %}
</section>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Eliminar Mascota</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Esta seguro de querer Eliminar a {{object.name|upper}}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <form action="{% url 'mascota_eliminar' pk=object.pk  %}" method="Post">
        {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Eliminar"/>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/detail_persona.html
{% extends 'base.html' %}
{% block content %}
<section class="col-12 col-md-8 mx-auto">
    {% if object %}
        <section class="alert alert-light w-md-75 mx-auto mt-5" role="alert">
            <span style="font-size:22px; font-style:italic;" class="d-flex justify-content-center font-weight-lighter mx-auto">
                <p> <strong>Datos Persona:</strong></p>
            </span>
            <p style="font-size:18px;" class="font-weight-lighter">Nombre: {{object.name|upper}} {{object.last_name|upper}}</p>
            <p style="font-size:18px;" class="font-weight-lighter">Edad: {{object.age}} años</p>
            <p style="font-size:18px;" class="font-weight-lighter">Email: {{object.email}}</p>
            <span class="d-flex">
                <p style="font-size:18px;" class="font-weight-lighter">Telefono:</p>
                <span class="">
                    {% if object.telephone_set.all %}
                        {% for telefono in object.telephone_set.all %}
                            <p style="font-size:18px; font-style:italic; margin-left: 1rem;" class="font-weight-lighter">
                                {{ telefono.number }} {{telefono.get_sort_display|lower}}
                            </p>
                        {% endfor %}
                    {% else %}
                        <p style="font-size:18px; font-style:italic; margin-left: 1rem;" class="font-weight-lighter">No tiene numeros Telefonico(s) registrado(s)</p>
                    {% endif %}
                </span>
            </span>
            <section style="font-size:22px; font-style:italic;" class="d-flex justify-content-center font-weight-lighter mx-auto">
                <p><strong>Mascotas Adoptadas:</strong></p>
            </section>
            <section style="font-size:18px;" class="font-weight-lighter">
                    {% if object.pet_set.all %}
                        {% for mascota in object.pet_set.all %}
                            {{mascota|upper}},
                        {% endfor %}
                    {% else %}
                        <p>{{object.name}}. Aun no ha Adoptado :(</p>
                    {% endif %}
            </section>
            <hr>
            <section style="display: flex; justify-content: space-between;">
                <section>
                 
                    <i><a style="font-size: 10px;" class="btn btn-light" href="{% url 'persona_actualizar' pk=object.pk  %}" role="button">EDITAR</a></i>
                    <button type="button" class="btn btn-light" data-toggle="modal" data-target="#exampleModal" style="font-size: 10px;">
                        ELIMINAR
                    </button>
                   
                </section>
                <a href="{% url 'mascotas_listar'%}" class="btn btn-primary">Adoptar</a>
            </section>
        </section>
    {% else %}
    <h1>No se encontro mascota</h1>
    {% endif %}
</section>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Eliminar Persona</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Esta seguro de querer Eliminar a {{object.name|upper}} {{object.last_name|upper}}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <form action="{% url 'persona_eliminar' pk=object.pk  %}" method="Post">
        {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Eliminar"/>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/list_mascotas.html
{% extends 'base.html'%}

{% block content %}
    <section class="table-responsive">
        {% if object_list %}
            <span style="font-size:22px; font-style:italic;" class="title d-flex justify-content-center font-weight-lighter mx-auto">
                <p> <strong>Mascotas:</strong></p>
            </span>
            <table class="table table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Nombre</td>
                        <th scope="col">Sexo</td>
                        <th scope="col">Edad</td>
                        <th scope="col">Fecha de Rescate</td>
                        <th scope="col">Adoptado</td>
                        <th scope="col">Accion</td>
                    </tr>
                </thead>
                {% for mascota in object_list%}
                <tr>
                    <td>{{mascota.name}}</td>
                    <td>{{mascota.get_sex_display}}</td>
                    <td>{{mascota.aproximated_ege}}</td>
                    <td>{{mascota.rescue_date}}</td>
                    <td>
                        {% if mascota.persons %}
                            <span><i class="fa fa-check icon-adopted"></i></span>
                        {% else %}
                            <span><i class="fa fa-shopping-basket icon-no-adopted"></i></span>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'mascota_detalle' pk=mascota.pk %}" type="button" class="btn btn-info">Ver mas</a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        {% else %}
            <h1>NO SE ENCONTRATON REGISTROS :(</h1>
        {% endif %}
    </section>
    <section class="d-flex justify-content-end">
            <a href="{% url 'mascota_crear' %}"><i class="fa fa-plus-circle"></i></a>
    </section>
{% endblock %}

templates/listar_personas.html
{% extends 'base.html'%}

{% block content %}
    <section class="table-responsive">
        {% if object_list %}
            <span style="font-size:22px; font-style:italic;" class="title d-flex justify-content-center font-weight-lighter mx-auto">
                <p> <strong>Personas:</strong></p>
            </span>
            <table class="table table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Nombre</td>
                        <th scope="col">Apellido</td>
                        <th scope="col">Email</td>
                        <th scope="col">Numero Telefonico</td>
                        <th scope="col">Acciones</td>
                    </tr>
                </thead>
                {% for persona in object_list%}
                <tr>
                    <td class="vertical-middle">
                        {{persona.name}}
                    </td>
                    <td class="vertical-middle">
                        {{persona.last_name}}
                    </td>
                    <td class="vertical-middle">
                        {{persona.email}}
                    </td>
                    {% if persona.telephone_set.all %}
                        <td class="vertical-middle">
                            {% for telefono in persona.telephone_set.all %}
                                <p>{{telefono.number}}</p>
                            {% endfor %}
                        </td>
                    {% else %}
                        <td>
                            <p>---</p>
                        </td>
                    {% endif %}
                    <td class="vertical-middle">
                        <a href="{% url 'persona_detalle' pk=persona.pk %}" type="button" class="btn btn-info">Ver mas</a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        {% else %}
            <h1>NO SE ENCONTRARON REGISTROS :(</h1>
        {% endif %}
    </section>
    <section class="d-flex justify-content-end">
            <a href="{% url 'persona_crear' %}"><i class="fa fa-plus-circle"></i></a>
    </section>
{% endblock %}